name: Pull Request Summary Example
author: tkgstrator 
description: Generating explanation of PR which has been opened by the developer.
inputs:
  OPENAI_API_KEY:
    description: OpenAI API key
    required: true
  GITHUB_TOKEN:
    description: Github Token
    required: true
runs:
  using: 'bun'
  main: 'dist/index.js'
