name: PR summary sample
author: Karthikeyan
description: Generating explanation of PR which has been opened by the developer.
inputs:
  OPENAI_API_KEY:
    description: OpenAI API key
    required: true
  GITHUB_TOKEN:
    description: Github Token
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
