name: Set Label to Pull Request

inputs:
  semver:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const { SEMVER } = process.env
          github.rest.issues.setLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            labels: [SEMVER]
          });
      env:
        SEMVER: ${{ inputs.semver }}
