name: Check Version Update with Pull Request

inputs:
  path:
    description: 'Path to package.json'
    required: false
    default: '.'
outputs:
  semver:
    description: 'Semantic Versioning'
    value: ${{ steps.check-version-update.outputs.semver }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.base_ref }}

    - name: Current Version
      id: current_version
      shell: bash
      run: |
        echo "version=$(cat ${{ inputs.path }}/package.json | jq -r '.version')" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Release Version
      id: release_version
      shell: bash
      run: |
        echo "version=$(cat ${{ inputs.path }}/package.json | jq -r '.version')" >> $GITHUB_OUTPUT

    - name: Check version update
      id: check-version-update
      shell: bash
      run: |
        release_version=${{ steps.release_version.outputs.version }}
        release_ver_array=(${release_version//./ })
        current_version=${{ steps.current_version.outputs.version }}
        current_ver_array=(${current_version//./ })
        if [ ${release_ver_array[0]} -gt ${current_ver_array[0]} ]; then echo "semver=Semver-Major" >> "$GITHUB_OUTPUT"; exit 0; fi
        if [ ${release_ver_array[0]} -eq ${current_ver_array[0]} ] && [ ${release_ver_array[1]} -gt ${current_ver_array[1]} ]; then echo "semver=Semver-Minor" >> "$GITHUB_OUTPUT"; exit 0; fi
        if [ ${release_ver_array[0]} -eq ${current_ver_array[0]} ] && [ ${release_ver_array[1]} -eq ${current_ver_array[1]} ] && [ ${release_ver_array[2]} -gt ${current_ver_array[2]} ]; then echo "semver=Semver-Patch" >> "$GITHUB_OUTPUT"; exit 0; fi
        echo "Please update version in package.json"
        exit 1
