name: Get Version from Package.json

inputs:
  ref:
    description: 'Branch name'
    required: false
    default: ${{ github.ref }}
  path:
    description: 'Path to package.json'
    required: false
    default: '.'
outputs:
  version:
    description: 'Semantic Versioning'
    value: ${{ steps.package_version.outputs.version }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - id: package_version
      shell: bash
      run: |
        echo "version=$(cat ${{ inputs.path }}/package.json | jq -r '.version')" >> $GITHUB_OUTPUT

    - shell: bash
      run: |
        echo ${{ steps.package_version.outputs.version }}
